language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - mkdir -p build/codecoverage
  - mkdir -p build/testresults
  - composer install --dev --prefer-source

script:
  - ./vendor/bin/phpunit --log-junit build/testresults/junit.xml --coverage-xml build/codecoverage test
  - ./vendor/bin/phpcs --standard=PSR2 ./src
  
