language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - mkdir -p build/codecoverage
  - mkdir -p build/testresults
  - composer install --dev --prefer-source

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/clover.xml
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php build/coverage-checker.php build/clover.xml 70; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != '5.3' ]; then ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/; fi"
  
after_script:
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php ocular.phar code-coverage:upload --format=php-clover ./build/clover.xml; fi"